FROM golang:latest

RUN apt-get update

RUN apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    libseccomp2 \
    software-properties-common -y

RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"

RUN apt-get update

RUN apt-get install docker-ce-cli

ADD "self-deploy" "self-deploy"

CMD ["./self-deploy", "--deploy"]
